// src/utils/importMembers.js
import { collection, addDoc } from 'firebase/firestore';
import { db } from './firebase';

const members = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    dateOfBirth: "1930-01-01",
    dateOfDeath: "1990-01-01",
    placeOfBirth: "New York, USA",
    placeOfResidence: "New York, USA",
    phoneNumber: "+1-555-1234",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Farmer",
  },
  {
    name: "Jane Doe",
    email: "jane.doe@example.com",
    dateOfBirth: "1932-02-02",
    dateOfDeath: "1995-02-02",
    placeOfBirth: "Boston, USA",
    placeOfResidence: "New York, USA",
    phoneNumber: "+1-555-5678",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Homemaker",
  },
  
  {
    name: "Michael Doe",
    email: "michael.doe@example.com",
    dateOfBirth: "1955-03-03",
    dateOfDeath: "2015-03-03",
    placeOfBirth: "New York, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-9012",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Engineer",
  },
  {
    name: "Emily Doe",
    email: "emily.doe@example.com",
    dateOfBirth: "1958-04-04",
    dateOfDeath: "2020-04-04",
    placeOfBirth: "New York, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-3456",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Teacher",
  },
  {
    name: "James Doe",
    email: "james.doe@example.com",
    dateOfBirth: "1960-05-05",
    dateOfDeath: "2018-05-05",
    placeOfBirth: "New York, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-7890",
    gender: "Male",
    maritalStatus: "Married",
  },
  // Spouses for second generation
  {
    name: "Anna Smith",
    email: "anna.smith@example.com",
    dateOfBirth: "1960-06-06",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-1122",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Nurse",
  },
  {
    id: "7",
    name: "Robert Brown",
    email: "robert.brown@example.com",
    dateOfBirth: "1961-07-07",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-5566",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Lawyer",
  },
  {
    name: "Laura Green",
    email: "laura.green@example.com",
    dateOfBirth: "1962-08-08",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-6677",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Graphic Designer",
  },


  {
    name: "David Doe",
    email: "david.doe@example.com",
    dateOfBirth: "1980-09-09",
    dateOfDeath: "2023-09-09",
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-3344",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Chef",
  },
  {
    name: "Sarah Doe",
    email: "sarah.doe@example.com",
    dateOfBirth: "1982-10-10",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-4455",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Doctor",
  },
  {
    name: "Daniel Brown",
    email: "daniel.brown@example.com",
    dateOfBirth: "1983-11-11",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-5566",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Engineer",
  },
  {
    name: "Emma Brown",
    email: "emma.brown@example.com",
    dateOfBirth: "1985-12-12",
    dateOfDeath: "2022-12-12",
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-6677",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Teacher",
  },
  {
    name: "Paul Green",
    email: "paul.green@example.com",
    dateOfBirth: "1986-01-13",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-7788",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Firefighter",
  },
  {
    name: "Laura Green",
    email: "laura.green@example.com",
    dateOfBirth: "1988-02-14",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-8899",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Architect",
  },
  // Spouses for third generation
  {
    name: "Rachel White",
    email: "rachel.white@example.com",
    dateOfBirth: "1981-03-15",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-9900",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Pharmacist",
  },
  {
    name: "Christopher Lee",
    email: "christopher.lee@example.com",
    dateOfBirth: "1983-04-16",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-0011",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Lawyer",
  },
  {
    name: "Amanda White",
    email: "amanda.white@example.com",
    dateOfBirth: "1984-05-17",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-2233",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Journalist",
  },
  {
    name: "Matthew Black",
    email: "matthew.black@example.com",
    dateOfBirth: "1986-06-18",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-3345",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Mechanic",
  },
  {
    name: "Natalie Green",
    email: "natalie.green@example.com",
    dateOfBirth: "1987-07-19",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-5566",
    gender: "Female",
    maritalStatus: "Married",
    occupation: "Teacher",
  },
  {
    name: "Andrew Johnson",
    email: "andrew.johnson@example.com",
    dateOfBirth: "1988-08-20",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-7789",
    gender: "Male",
    maritalStatus: "Married",
    occupation: "Pilot",
  },


  
  {
    name: "Sophia White",
    email: "sophia.white@example.com",
    dateOfBirth: "2010-05-21",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-9901",
    gender: "Female",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Aiden White",
    email: "aiden.white@example.com",
    dateOfBirth: "2012-06-22",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-9902",
    gender: "Male",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Liam Lee",
    email: "liam.lee@example.com",
    dateOfBirth: "2010-07-23",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-0012",
    gender: "Male",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Emma Lee",
    email: "emma.lee@example.com",
    dateOfBirth: "2012-08-24",
    dateOfDeath: null,
    placeOfBirth: "Chicago, USA",
    placeOfResidence: "Chicago, USA",
    phoneNumber: "+1-555-0013",
    gender: "Female",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Ethan Brown",
    email: "ethan.brown@example.com",
    dateOfBirth: "2011-09-25",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-2234",
    gender: "Male",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Olivia Brown",
    email: "olivia.brown@example.com",
    dateOfBirth: "2013-10-26",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-2235",
    gender: "Female",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Mason Black",
    email: "mason.black@example.com",
    dateOfBirth: "2011-11-27",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-3346",
    gender: "Male",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Isabella Black",
    email: "isabella.black@example.com",
    dateOfBirth: "2013-12-28",
    dateOfDeath: null,
    placeOfBirth: "Los Angeles, USA",
    placeOfResidence: "Los Angeles, USA",
    phoneNumber: "+1-555-3347",
    gender: "Female",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Jacob Green",
    email: "jacob.green@example.com",
    dateOfBirth: "2012-01-29",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-5567",
    gender: "Male",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Mia Green",
    email: "mia.green@example.com",
    dateOfBirth: "2014-02-30",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-5568",
    gender: "Female",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "William Johnson",
    email: "william.johnson@example.com",
    dateOfBirth: "2013-03-31",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-7789",
    gender: "Male",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    name: "Ava Johnson",
    email: "ava.johnson@example.com",
    dateOfBirth: "2015-04-01",
    dateOfDeath: null,
    placeOfBirth: "Houston, USA",
    placeOfResidence: "Houston, USA",
    phoneNumber: "+1-555-7790",
    gender: "Female",
    maritalStatus: "Single",
    occupation: "Student",
  }
]


const importMembers = async () => {
  try {
    for (const member of members) {
      await addDoc(collection(db, 'members'), member);
    }
    console.log("Members imported successfully");
  } catch (error) {
    console.error("Error importing members: ", error);
  }
};

export default importMembers